name: cleanup

on:
  pull_request:
    types: [ closed ]

jobs:
  delete-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: [ 'success', 'failure' ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'

    # Dependencies
    - run: npm ci
    - run: npm run build

    - name: extract branch name
      id: get_branch
      shell: bash
      env:
        PR_HEAD: ${{ github.head_ref }}
      run: echo "branch=$(echo ${PR_HEAD#refs/heads/} | tr / -)" >> $GITHUB_OUTPUT

    - name: delete environment
      uses: ./
      with:
        step: delete-env
        token: ${{ secrets.GITHUB_TOKEN }}
        env: integration-test-${{ steps.get_branch.outputs.branch }}-${{ matrix.scenario }}
        debug: true
